//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    public static func createWidget(widgetID: Int, parameters: CreateWidgetParameters, name: String) -> Request<WidgetEnvelope> {
        Request(path: "/widgets/\(widgetID)", method: "POST", query: parameters.asQuery, body: ["name": name], id: "createWidget")
    }

    public struct CreateWidgetParameters {
        public var search: String
        public var limit: Int32?
        public var isExpand: Bool?

        public init(search: String, limit: Int32? = nil, isExpand: Bool? = nil) {
            self.search = search
            self.limit = limit
            self.isExpand = isExpand
        }

        public var asQuery: [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(search, forKey: "search")
            encoder.encode(limit, forKey: "limit")
            encoder.encode(isExpand, forKey: "expand")
            return encoder.items
        }
    }
}
