//
// Generated by openapi-generator
//

import Foundation

/// Widget model
///
/// Entity config fixture
@available(*, deprecated, message: "Deprecated")
public struct Widget: Codable {
    public var zeta: String
    @available(*, deprecated, message: "Deprecated")
    public var isActive: Bool
    public var id: Int64
    public var status: Status
    public var metadata: [String: AnyJSON]?
    public var count: Int32?
    public var ratio: Float?
    public var link: URL?
    public var created: Date?

    public enum Status: String, Codable, CaseIterable {
        case ready
        case notReady = "not-ready"
    }

    public init(zeta: String, isActive: Bool? = nil, id: Int64, status: Status, metadata: [String: AnyJSON]? = nil, count: Int32? = nil, ratio: Float? = nil, link: URL? = nil, created: Date? = nil) {
        self.zeta = zeta
        self.isActive = isActive ?? true
        self.id = id
        self.status = status
        self.metadata = metadata
        self.count = count
        self.ratio = ratio
        self.link = link
        self.created = created
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.zeta = try values.decode(String.self, forKey: "zeta")
        self.isActive = try values.decodeIfPresent(Bool.self, forKey: "active") ?? true
        self.id = try values.decode(Int64.self, forKey: "id")
        self.status = try values.decode(Status.self, forKey: "status")
        self.metadata = try values.decodeIfPresent([String: AnyJSON].self, forKey: "metadata")
        self.count = try values.decodeIfPresent(Int32.self, forKey: "count")
        self.ratio = try values.decodeIfPresent(Float.self, forKey: "ratio")
        self.link = try values.decodeIfPresent(URL.self, forKey: "link")
        self.created = try values.decodeIfPresent(Date.self, forKey: "created")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(zeta, forKey: "zeta")
        try values.encodeIfPresent(isActive, forKey: "active")
        try values.encode(id, forKey: "id")
        try values.encode(status, forKey: "status")
        try values.encodeIfPresent(metadata, forKey: "metadata")
        try values.encodeIfPresent(count, forKey: "count")
        try values.encodeIfPresent(ratio, forKey: "ratio")
        try values.encodeIfPresent(link, forKey: "link")
        try values.encodeIfPresent(created, forKey: "created")
    }
}
