//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    public static var pets: Pets {
        Pets(path: "/pets")
    }

    public struct Pets {
        /// Path: `/pets`
        public let path: String
    }
}
