//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    /// Get modern item
    public static var getModernItem: Request<Void> {
        Request(path: "/modern", method: "GET", id: "getModernItem")
    }
}
