//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    public static var legacy: Legacy {
        Legacy(path: "/legacy")
    }

    public struct Legacy {
        /// Path: `/legacy`
        public let path: String
    }
}
