//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    public static var pets: Pets {
        Pets(path: "/pets")
    }

    public struct Pets {
        /// Path: `/pets`
        public let path: String

        /// List all pets
        public func get(limit: Int32? = nil) -> Request<[Pet]> {
            Request(path: path, method: "GET", query: makeGetQuery(limit), id: "listPets")
        }

        private func makeGetQuery(_ limit: Int32?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(limit, forKey: "limit")
            return encoder.items
        }

        /// Create a pet
        public var post: Request<Void> {
            Request(path: path, method: "POST", id: "createPets")
        }
    }
}
