//
// Generated by openapi-generator
//

import Foundation

public struct Organization: Codable {
    /// Organization address schema
    ///
    /// Organization-specific address property description remains on the property.
    public var address: SharedAddress?
    public var metadata: Metadata?

    public struct Metadata: Codable {
        public var source: String?

        public init(source: String? = nil) {
            self.source = source
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.source = try values.decodeIfPresent(String.self, forKey: "source")
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encodeIfPresent(source, forKey: "source")
        }
    }

    public init(address: SharedAddress? = nil, metadata: Metadata? = nil) {
        self.address = address
        self.metadata = metadata
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.address = try values.decodeIfPresent(SharedAddress.self, forKey: "address")
        self.metadata = try values.decodeIfPresent(Metadata.self, forKey: "metadata")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(address, forKey: "address")
        try values.encodeIfPresent(metadata, forKey: "metadata")
    }
}
