//
// Generated by openapi-generator
//

import Foundation

/// User address schema
///
/// User-specific address property description is copied to the shared type.
public struct SharedAddress: Codable {
    public var city: String?
    public var street: String?

    public init(city: String? = nil, street: String? = nil) {
        self.city = city
        self.street = street
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.city = try values.decodeIfPresent(String.self, forKey: "city")
        self.street = try values.decodeIfPresent(String.self, forKey: "street")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(city, forKey: "city")
        try values.encodeIfPresent(street, forKey: "street")
    }
}
