//
// Generated by openapi-generator
//

import Foundation

struct Error: Codable {
    var code: Int32
    var message: String

    init(code: Int32, message: String) {
        self.code = code
        self.message = message
    }

    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.code = try values.decode(Int32.self, forKey: "code")
        self.message = try values.decode(String.self, forKey: "message")
    }

    func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(code, forKey: "code")
        try values.encode(message, forKey: "message")
    }
}
