//
// Generated by openapi-generator
//

import Foundation

/// A pet title
///
/// A pet description
struct Pet: Codable {
    var id: Int64
    var name: String
    var tag: String?

    init(id: Int64, name: String, tag: String? = nil) {
        self.id = id
        self.name = name
        self.tag = tag
    }

    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Int64.self, forKey: "id")
        self.name = try values.decode(String.self, forKey: "name")
        self.tag = try values.decodeIfPresent(String.self, forKey: "tag")
    }

    func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(name, forKey: "name")
        try values.encodeIfPresent(tag, forKey: "tag")
    }
}
