//
// Generated by openapi-generator
//

import Foundation

struct Store: Codable {
    var pets: [Pet]

    init(pets: [Pet]) {
        self.pets = pets
    }

    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.pets = try values.decode([Pet].self, forKey: "pets")
    }

    func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(pets, forKey: "pets")
    }
}
