//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    /// Create a pet
    public static var createPets: Request<Void> {
        Request(path: "/pets", method: "POST", id: "createPets")
    }
}
