//
// Generated by openapi-generator
//

import Foundation

public struct Info: Sendable {
    public var title: String {
        "Config Info Options"
    }
    public var description: String {
        "Full info fixture"
    }
    public var termsOfService: URL {
        URL(string: "https://example.com/terms")!
    }
    public var contact: Contact {
        Info.Contact(name: "API Support", url: URL(string: "https://example.com/support")!, email: "support@example.com")
    }
    public var license: License {
        Info.License(name: "Example License", url: URL(string: "https://example.com/license")!)
    }
    public var version: Version {
        "9.8.7"
    }

    public struct Version: Comparable, CustomStringConvertible, ExpressibleByStringLiteral, Sendable {
        public let major: Int
        public let minor: Int
        public let patch: Int

        public var description: String {
            "\(major).\(minor).\(patch)"
        }

        public var majorMinor: Version {
            Version(major: major, minor: minor, patch: 0)
        }

        public init(stringLiteral value: StringLiteralType) {
            let parsed = Version.parse(value: value)
            self.major = parsed.major
            self.minor = parsed.minor
            self.patch = parsed.patch
        }

        public init(major: Int, minor: Int, patch: Int) {
            self.major = max(0, major)
            self.minor = max(0, minor)
            self.patch = max(0, patch)
        }

        private static func parse(value: String) -> (major: Int, minor: Int, patch: Int) {
            let components = value.split(separator: ".")

            guard components.count == 3 else {
                return (0, 0, 0)
            }

            guard let major = Int(components[0]),
                  let minor = Int(components[1]),
                  let patch = Int(components[2])
            else {
                return (0, 0, 0)
            }

            guard major >= 0 && minor >= 0 && patch >= 0 else {
                return (0, 0, 0)
            }

            return (major, minor, patch)
        }

        public static func == (lhs: Version, rhs: Version) -> Bool {
            lhs.major == rhs.major && lhs.minor == rhs.minor && lhs.patch == rhs.patch
        }

        public static func < (lhs: Version, rhs: Version) -> Bool {
            if lhs.major != rhs.major {
                return lhs.major < rhs.major
            }
            if lhs.minor != rhs.minor {
                return lhs.minor < rhs.minor
            }
            return lhs.patch < rhs.patch
        }
    }

    public struct Contact: Sendable {
        public let name: String
        public let url: URL
        public let email: String

        public init(
            name: String,
            url: URL,
            email: String
        ) {
            self.name = name
            self.url = url
            self.email = email
        }
    }

    public struct License: Sendable {
        public let name: String
        public let url: URL

        public init(
            name: String,
            url: URL
        ) {
            self.name = name
            self.url = url
        }
    }
}
