//
// Generated by openapi-generator
//

import Foundation

public struct CatalogItemGroup: Codable {
    public var attributes: Attributes?
    public var data: [DataItem]?
    public var id: String?

    public struct Attributes: Codable {
        public var groupKind: String?

        public init(groupKind: String? = nil) {
            self.groupKind = groupKind
        }

        public enum CodingKeys: String, CodingKey {
            case groupKind = "groupKind"
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: CodingKeys.self)
            self.groupKind = try values.decodeIfPresent(String.self, forKey: .groupKind)
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: CodingKeys.self)
            try values.encodeIfPresent(groupKind, forKey: .groupKind)
        }
    }

    public struct DataItem: Codable {
        public var position: Int?
        public var region: String?

        public init(position: Int? = nil, region: String? = nil) {
            self.position = position
            self.region = region
        }

        public enum CodingKeys: String, CodingKey {
            case position = "position"
            case region = "region"
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: CodingKeys.self)
            self.position = try values.decodeIfPresent(Int.self, forKey: .position)
            self.region = try values.decodeIfPresent(String.self, forKey: .region)
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: CodingKeys.self)
            try values.encodeIfPresent(position, forKey: .position)
            try values.encodeIfPresent(region, forKey: .region)
        }
    }

    public init(attributes: Attributes? = nil, data: [DataItem]? = nil, id: String? = nil) {
        self.attributes = attributes
        self.data = data
        self.id = id
    }

    public enum CodingKeys: String, CodingKey {
        case attributes = "attributes"
        case data = "data"
        case id = "id"
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        self.attributes = try values.decodeIfPresent(Attributes.self, forKey: .attributes)
        self.data = try values.decodeIfPresent([DataItem].self, forKey: .data)
        self.id = try values.decodeIfPresent(String.self, forKey: .id)
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: CodingKeys.self)
        try values.encodeIfPresent(attributes, forKey: .attributes)
        try values.encodeIfPresent(data, forKey: .data)
        try values.encodeIfPresent(id, forKey: .id)
    }
}
