//
// Generated by openapi-generator
//

import Foundation

public struct CatalogItemGroupDataItem: Codable {
    public var position: Int?
    public var region: String?

    public init(position: Int? = nil, region: String? = nil) {
        self.position = position
        self.region = region
    }

    public enum CodingKeys: String, CodingKey {
        case position = "position"
        case region = "region"
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        self.position = try values.decodeIfPresent(Int.self, forKey: .position)
        self.region = try values.decodeIfPresent(String.self, forKey: .region)
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: CodingKeys.self)
        try values.encodeIfPresent(position, forKey: .position)
        try values.encodeIfPresent(region, forKey: .region)
    }
}
