//
// Generated by openapi-generator
//

import Foundation

public struct CatalogItem: Codable {
    public var attributes: CatalogItemAttributes?
    public var data: [CatalogItemDataItem]?
    public var id: String?

    public init(attributes: CatalogItemAttributes? = nil, data: [CatalogItemDataItem]? = nil, id: String? = nil) {
        self.attributes = attributes
        self.data = data
        self.id = id
    }

    public enum CodingKeys: String, CodingKey {
        case attributes = "attributes"
        case data = "data"
        case id = "id"
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        self.attributes = try values.decodeIfPresent(CatalogItemAttributes.self, forKey: .attributes)
        self.data = try values.decodeIfPresent([CatalogItemDataItem].self, forKey: .data)
        self.id = try values.decodeIfPresent(String.self, forKey: .id)
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: CodingKeys.self)
        try values.encodeIfPresent(attributes, forKey: .attributes)
        try values.encodeIfPresent(data, forKey: .data)
        try values.encodeIfPresent(id, forKey: .id)
    }
}
