//
// Generated by openapi-generator
//

import Foundation

public struct CatalogItemGroupAttributes: Codable {
    public var groupKind: String?

    public init(groupKind: String? = nil) {
        self.groupKind = groupKind
    }

    public enum CodingKeys: String, CodingKey {
        case groupKind = "groupKind"
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        self.groupKind = try values.decodeIfPresent(String.self, forKey: .groupKind)
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: CodingKeys.self)
        try values.encodeIfPresent(groupKind, forKey: .groupKind)
    }
}
