//
// Generated by openapi-generator
//

import Foundation

public struct CatalogItemDataItem: Codable {
    public var digest: String?
    public var size: Int?

    public init(digest: String? = nil, size: Int? = nil) {
        self.digest = digest
        self.size = size
    }

    public enum CodingKeys: String, CodingKey {
        case digest = "digest"
        case size = "size"
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        self.digest = try values.decodeIfPresent(String.self, forKey: .digest)
        self.size = try values.decodeIfPresent(Int.self, forKey: .size)
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: CodingKeys.self)
        try values.encodeIfPresent(digest, forKey: .digest)
        try values.encodeIfPresent(size, forKey: .size)
    }
}
