//
// Generated by openapi-generator
//

import Foundation

public struct CatalogItemAttributes: Codable {
    public var displayName: String?
    public var resourceURL: String?

    public init(displayName: String? = nil, resourceURL: String? = nil) {
        self.displayName = displayName
        self.resourceURL = resourceURL
    }

    public enum CodingKeys: String, CodingKey {
        case displayName = "displayName"
        case resourceURL = "resourceUrl"
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        self.displayName = try values.decodeIfPresent(String.self, forKey: .displayName)
        self.resourceURL = try values.decodeIfPresent(String.self, forKey: .resourceURL)
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: CodingKeys.self)
        try values.encodeIfPresent(displayName, forKey: .displayName)
        try values.encodeIfPresent(resourceURL, forKey: .resourceURL)
    }
}
