//
// Generated by openapi-generator
//

import Foundation

public enum Payload: Codable {
    case cat(SharedAnimal)
    case dog(SharedAnimal)

    public init(from decoder: Decoder) throws {

        struct Discriminator: Decodable {
            let _Type: String
        }

        let container = try decoder.singleValueContainer()
        let discriminatorValue = try container.decode(Discriminator.self)._Type

        switch discriminatorValue {
        case "cat": self = try .cat(container.decode(SharedAnimal.self))
        case "dog": self = try .dog(container.decode(SharedAnimal.self))
        default:
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Discriminator value '\(discriminatorValue)' does not match any expected values (cat, dog)."
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case let .cat(value): try container.encode(value)
        case let .dog(value): try container.encode(value)
        }
    }
}
