//
// Generated by openapi-generator
//

import Foundation

public struct SharedAnimal: Codable {
    public var name: String?
    public var type: String?

    public init(name: String? = nil, type: String? = nil) {
        self.name = name
        self.type = type
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.name = try values.decodeIfPresent(String.self, forKey: "name")
        self.type = try values.decodeIfPresent(String.self, forKey: "Type")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(name, forKey: "name")
        try values.encodeIfPresent(type, forKey: "Type")
    }
}
