import Foundation
import Yams

public struct Configuration: Decodable, Sendable {
    public enum Generate: String, Codable, Sendable {
        case entities
        case package
        case paths
    }

    public enum Access: String, Codable, Sendable {
        case `internal`
        case `public`
    }

    public var access: Access = .public
    public var acronyms: [String] = Self.defaultAcronyms
    public var comments: Comments = .init()
    public var dataTypes: DataTypes = .init()
    public var entities: Entities = .init()
    public var extensions: Extensions = .init()
    public var fileHeader: String = Self.defaultFileHeaderComment
    public var generate: Set<Generate> = [.entities, .paths]
    public var inlineTypealiases: Bool = true
    public var module: String = "MyOpenAPISDK"
    public var paths: Paths = .init()
    public var pluralizeProperties: Bool = true
    public var rename: Rename = .init()
    public var useSwiftyPropertyNames: Bool = true

    public init() {}

    enum CodingKeys: String, CodingKey {
        case access
        case acronyms
        case comments
        case dataTypes
        case entities
        case extensions
        case fileHeader
        case generate
        case inlineTypealiases
        case module
        case paths
        case pluralizeProperties
        case rename
        case useSwiftyPropertyNames
    }

    public init(from decoder: Decoder) throws {
        self.init()
        let container = try decoder.container(keyedBy: CodingKeys.self)
        access = try container.decodeIfPresent(Access.self, forKey: .access) ?? access
        acronyms = try container.decodeIfPresent([String].self, forKey: .acronyms) ?? acronyms
        comments = try container.decodeIfPresent(Comments.self, forKey: .comments) ?? comments
        dataTypes = try container.decodeIfPresent(DataTypes.self, forKey: .dataTypes) ?? dataTypes
        entities = try container.decodeIfPresent(Entities.self, forKey: .entities) ?? entities
        extensions = try container.decodeIfPresent(Extensions.self, forKey: .extensions) ?? extensions
        fileHeader = try container.decodeIfPresent(String.self, forKey: .fileHeader) ?? fileHeader
        generate = try container.decodeIfPresent(Set<Generate>.self, forKey: .generate) ?? generate
        inlineTypealiases = try container.decodeIfPresent(Bool.self, forKey: .inlineTypealiases) ?? inlineTypealiases
        module = try container.decodeIfPresent(String.self, forKey: .module) ?? module
        paths = try container.decodeIfPresent(Paths.self, forKey: .paths) ?? paths
        pluralizeProperties = try container.decodeIfPresent(Bool.self, forKey: .pluralizeProperties) ?? pluralizeProperties
        rename = try container.decodeIfPresent(Rename.self, forKey: .rename) ?? rename
        useSwiftyPropertyNames = try container.decodeIfPresent(Bool.self, forKey: .useSwiftyPropertyNames) ?? useSwiftyPropertyNames
    }
}

public extension Configuration {
    static let defaultAcronyms = [
        "url",
        "id",
        "html",
        "ssl",
        "tls",
        "https",
        "http",
        "dns",
        "ftp",
        "api",
        "uuid",
        "json"
    ]

    static let defaultFileHeaderComment = """
    //
    // Generated by openapi-generator
    //
    """

    var commentsEnabled: Bool {
        !comments.options.isEmpty
    }
}

public enum CommentOption: String, Codable, Sendable {
    case capitalized
    case description
    case title
}

public enum DeprecationAnnotation: String, Codable, Sendable {
    case annotation
    case comment
    case none
    case remove
}

public struct Comments: Decodable, Sendable {
    public var annotateDeprecations: DeprecationAnnotation = .annotation
    public var options: Set<CommentOption> = [.title, .description, .capitalized]

    public init() {}

    enum CodingKeys: String, CodingKey {
        case annotateDeprecations
        case options
    }

    public init(from decoder: Decoder) throws {
        self.init()
        let container = try decoder.container(keyedBy: CodingKeys.self)
        annotateDeprecations = try container
            .decodeIfPresent(DeprecationAnnotation.self, forKey: .annotateDeprecations) ?? annotateDeprecations
        options = try container.decodeIfPresent(Set<CommentOption>.self, forKey: .options) ?? options
    }
}

public struct ComponentPath: RawRepresentable, Codable, Hashable, Sendable {
    public var parent: String
    public var child: String?

    public init(parent: String, child: String?) {
        self.parent = parent
        self.child = child
    }

    public init?(rawValue: String) {
        let components = rawValue.components(separatedBy: ".")
        switch components.count {
        case 1:
            self.init(parent: components[0], child: nil)
        case 2:
            self.init(parent: components[0], child: components[1])
        default:
            return nil
        }
    }

    public var rawValue: String {
        if let child {
            "\(parent).\(child)"
        } else {
            parent
        }
    }
}

public struct DataTypes: Decodable, Sendable {
    public var integer: [String: String] = [:]
    public var number: [String: String] = [:]
    public var string: [String: String] = [:]

    public init() {}

    enum CodingKeys: String, CodingKey {
        case integer
        case number
        case string
    }

    public init(from decoder: Decoder) throws {
        self.init()
        let container = try decoder.container(keyedBy: CodingKeys.self)
        integer = try container.decodeIfPresent([String: String].self, forKey: .integer) ?? integer
        number = try container.decodeIfPresent([String: String].self, forKey: .number) ?? number
        string = try container.decodeIfPresent([String: String].self, forKey: .string) ?? string
    }
}

public struct Entities: Decodable, Sendable {
    public enum CodingStrategy: String, Codable, Sendable {
        case codingKeys
        case stringCodingKey
    }

    public enum EntityType: String, Codable, Sendable {
        case `struct`
        case `class`
        case finalClass
    }

    public var automaticIdentifiable: Bool = false
    public var codingStrategy: CodingStrategy = .stringCodingKey
    public var conformances: Set<String> = ["Codable"]
    public var defaultType: EntityType = .struct
    public var defaultValues: Bool = true
    public var entityTypeOverrides: [String: EntityType] = [:]
    public var enumConformances: Set<String> = ["Codable", "CaseIterable"]
    public var exclude: Set<ComponentPath> = []
    public var filenameTemplate: String = "%0.swift"
    public var include: Set<String> = []
    public var indirectProperties: Set<String> = []
    public var inlineReferencedSchemas: Bool = true
    public var imports: Set<String> = ["Foundation"]
    public var memberwiseInit: Bool = true
    public var mutableProperties: Set<MutableProperties> = [.structs]
    public var nameTemplate: String = "%0"
    public var propertyTypeOverrides: [String: String] = [:]
    public var sortProperties: Bool = true
    public var stringEnums: Bool = true

    public init() {}

    enum CodingKeys: String, CodingKey {
        case automaticIdentifiable
        case codingStrategy
        case conformances
        case defaultType
        case defaultValues
        case entityTypeOverrides
        case enumConformances
        case exclude
        case filenameTemplate
        case include
        case indirectProperties
        case inlineReferencedSchemas
        case imports
        case memberwiseInit
        case mutableProperties
        case nameTemplate
        case propertyTypeOverrides
        case sortProperties
        case stringEnums
    }

    public init(from decoder: Decoder) throws {
        self.init()
        let container = try decoder.container(keyedBy: CodingKeys.self)
        automaticIdentifiable = try container.decodeIfPresent(Bool.self, forKey: .automaticIdentifiable) ?? automaticIdentifiable
        codingStrategy = try container.decodeIfPresent(CodingStrategy.self, forKey: .codingStrategy) ?? codingStrategy
        conformances = try container.decodeIfPresent(Set<String>.self, forKey: .conformances) ?? conformances
        defaultType = try container.decodeIfPresent(EntityType.self, forKey: .defaultType) ?? defaultType
        defaultValues = try container.decodeIfPresent(Bool.self, forKey: .defaultValues) ?? defaultValues
        entityTypeOverrides = try container.decodeIfPresent([String: EntityType].self, forKey: .entityTypeOverrides) ?? entityTypeOverrides
        enumConformances = try container.decodeIfPresent(Set<String>.self, forKey: .enumConformances) ?? enumConformances
        exclude = try container.decodeIfPresent(Set<ComponentPath>.self, forKey: .exclude) ?? exclude
        filenameTemplate = try container.decodeIfPresent(String.self, forKey: .filenameTemplate) ?? filenameTemplate
        include = try container.decodeIfPresent(Set<String>.self, forKey: .include) ?? include
        indirectProperties = try container.decodeIfPresent(Set<String>.self, forKey: .indirectProperties) ?? indirectProperties
        inlineReferencedSchemas = try container.decodeIfPresent(Bool.self, forKey: .inlineReferencedSchemas) ?? inlineReferencedSchemas
        imports = try container.decodeIfPresent(Set<String>.self, forKey: .imports) ?? imports
        memberwiseInit = try container.decodeIfPresent(Bool.self, forKey: .memberwiseInit) ?? memberwiseInit
        mutableProperties = try container.decodeIfPresent(Set<MutableProperties>.self, forKey: .mutableProperties) ?? mutableProperties
        nameTemplate = try container.decodeIfPresent(String.self, forKey: .nameTemplate) ?? nameTemplate
        propertyTypeOverrides = try container
            .decodeIfPresent([String: String].self, forKey: .propertyTypeOverrides) ?? propertyTypeOverrides
        sortProperties = try container.decodeIfPresent(Bool.self, forKey: .sortProperties) ?? sortProperties
        stringEnums = try container.decodeIfPresent(Bool.self, forKey: .stringEnums) ?? stringEnums
    }
}

public enum MutableProperties: String, Codable, Sendable {
    case structs
    case classes
}

public extension Entities {
    func preferredType(of entity: String) -> Entities.EntityType {
        entityTypeOverrides[entity] ?? defaultType
    }
}

public struct Paths: Decodable, Sendable {

    public var bodyTypeOverrides: [String: String] = [:]
    public var exclude: Set<String> = []
    public var filenameTemplate: String = "%0.swift"
    public var include: Set<String> = []
    public var imports: Set<String> = ["Foundation", "Get"]
    public var inlineQueryParameterLimit: Int? = 2
    public var inlineSimpleRequests: Bool = true
    public var namespace: String = "Paths"
    public var responseTypeOverrides: [String: String] = [:]

    public init() {}

    enum CodingKeys: String, CodingKey {
        case bodyTypeOverrides
        case exclude
        case filenameTemplate
        case include
        case imports
        case inlineQueryParameterLimit
        case inlineSimpleRequests
        case namespace
        case responseTypeOverrides
    }

    public init(from decoder: Decoder) throws {
        self.init()
        let container = try decoder.container(keyedBy: CodingKeys.self)
        bodyTypeOverrides = try container.decodeIfPresent([String: String].self, forKey: .bodyTypeOverrides) ?? bodyTypeOverrides
        exclude = try container.decodeIfPresent(Set<String>.self, forKey: .exclude) ?? exclude
        filenameTemplate = try container.decodeIfPresent(String.self, forKey: .filenameTemplate) ?? filenameTemplate
        include = try container.decodeIfPresent(Set<String>.self, forKey: .include) ?? include
        imports = try container.decodeIfPresent(Set<String>.self, forKey: .imports) ?? imports
        if container.contains(.inlineQueryParameterLimit) {
            inlineQueryParameterLimit = try container.decodeIfPresent(Int.self, forKey: .inlineQueryParameterLimit)
        }
        inlineSimpleRequests = try container.decodeIfPresent(Bool.self, forKey: .inlineSimpleRequests) ?? inlineSimpleRequests
        namespace = try container.decodeIfPresent(String.self, forKey: .namespace) ?? namespace
        responseTypeOverrides = try container
            .decodeIfPresent([String: String].self, forKey: .responseTypeOverrides) ?? responseTypeOverrides
    }
}

public struct Rename: Decodable, Sendable {
    public var enumCases: [String: String] = [:]
    public var entities: [String: String] = [:]
    public var operations: [String: String] = [:]
    public var parameters: [String: String] = [:]
    public var properties: [String: String] = [:]

    public init() {}

    enum CodingKeys: String, CodingKey {
        case enumCases
        case entities
        case operations
        case parameters
        case properties
    }

    public init(from decoder: Decoder) throws {
        self.init()
        let container = try decoder.container(keyedBy: CodingKeys.self)
        enumCases = try container.decodeIfPresent([String: String].self, forKey: .enumCases) ?? enumCases
        entities = try container.decodeIfPresent([String: String].self, forKey: .entities) ?? entities
        operations = try container.decodeIfPresent([String: String].self, forKey: .operations) ?? operations
        parameters = try container.decodeIfPresent([String: String].self, forKey: .parameters) ?? parameters
        properties = try container.decodeIfPresent([String: String].self, forKey: .properties) ?? properties
    }
}

public struct Extensions: Decodable, Sendable {
    public enum Emit: String, Codable, Sendable {
        case pathsNamespace
        case stringCodingKey
        case anyJSON
        case indirect
        case info
    }

    public var emit: Set<Emit> = [
        .pathsNamespace,
        .stringCodingKey,
        .anyJSON,
        .indirect,
        .info
    ]

    public init() {}

    enum CodingKeys: String, CodingKey {
        case emit
    }

    public init(from decoder: Decoder) throws {
        self.init()
        let container = try decoder.container(keyedBy: CodingKeys.self)
        emit = try container.decodeIfPresent(Set<Emit>.self, forKey: .emit) ?? emit
    }
}
