//
// Generated by openapi-generator
//

import CoreData
import Foundation
import Get
import HTTPHeaders

extension Paths {
    /// List all pets
    public static func listPets(limit: Int32? = nil) -> Request<[Pet]> {
        Request(path: "/pets", method: "GET", query: makeListPetsQuery(limit), id: "listPets")
    }

    private static func makeListPetsQuery(_ limit: Int32?) -> [(String, String?)] {
        let encoder = URLQueryEncoder()
        encoder.encode(limit, forKey: "limit")
        return encoder.items
    }
}
