//
// Generated by openapi-generator
//

import CoreData
import Foundation
import Get
import HTTPHeaders

extension Paths {
    /// Info for a specific pet
    public static func showPetByID(petID: String) -> Request<Pet> {
        Request(path: "/pets/\(petID)", method: "GET", id: "showPetById")
    }
}
