//
// Generated by openapi-generator
//

import Foundation
import Get

extension APIRoutes.Pets {
    public func petID(_ petID: String) -> WithPetID {
        WithPetID(path: "\(path)/\(petID)")
    }

    public struct WithPetID {
        /// Path: `/pets/{petId}`
        public let path: String

        /// Info for a specific pet
        public var get: Request<Pet> {
            Request(path: path, method: "GET", id: "showPetById")
        }
    }
}
