//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    public static var lastNames: LastNames {
        LastNames(path: "/last-names")
    }

    public struct LastNames {
        /// Path: `/last-names`
        public let path: String

        public var get: Request<Void> {
            Request(path: path, method: "GET", id: "getLastNames")
        }
    }
}
