//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    public static var lastNames2: LastNames2 {
        LastNames2(path: "/last_names")
    }

    public struct LastNames2 {
        /// Path: `/last_names`
        public let path: String

        public var get: Request<Void> {
            Request(path: path, method: "GET", id: "getLastNamesUnderscore")
        }
    }
}
