//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    public static func makeWidget(widgetID: Int, parameters: MakeWidgetParameters, name: String) -> Request<MakeWidgetResponse> {
        Request(path: "/widgets/\(widgetID)", method: "POST", query: parameters.asQuery, body: ["name": name], id: "makeWidget")
    }

    public struct MakeWidgetResponse: Codable {
        public var value: String?

        public init(value: String? = nil) {
            self.value = value
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.value = try values.decodeIfPresent(String.self, forKey: "value")
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encodeIfPresent(value, forKey: "value")
        }
    }

    public struct MakeWidgetParameters {
        public var search: String
        public var limit: Int32?
        public var isExpand: Bool?

        public init(search: String, limit: Int32? = nil, isExpand: Bool? = nil) {
            self.search = search
            self.limit = limit
            self.isExpand = isExpand
        }

        public var asQuery: [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(search, forKey: "search")
            encoder.encode(limit, forKey: "limit")
            encoder.encode(isExpand, forKey: "expand")
            return encoder.items
        }
    }
}
