//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    /// Info for a specific pet
    static func showPetByID(petID: String) -> Request<Pet> {
        Request(path: "/pets/\(petID)", method: "GET", id: "showPetById")
    }
}
