//
// Generated by openapi-generator
//

import Foundation

public struct Widget: Codable {
    public var otherValue: String

    public init(otherValue: String) {
        self.otherValue = otherValue
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.otherValue = try values.decode(String.self, forKey: "OtherValue")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(otherValue, forKey: "OtherValue")
    }
}
