//
// Generated by openapi-generator
//

import Foundation

public struct Collection: Codable {
    /// A longer description of the collection.
    /// This is also a comment, but on a new line using the \n line break.
    public var description: String
    /// The unique collection identifier.
    public var id: Int
    /// URLs to images for up to a maximum of four recipes in the collection.
    public var previewImageURLs: [URL]
    /// The number of recipes in this collection.
    /// This is also a comment, but on a new line using the \r line break.
    public var recipeCount: Int
    /// The title of the collection.
    public var title: String

    public init(description: String, id: Int, previewImageURLs: [URL], recipeCount: Int, title: String) {
        self.description = description
        self.id = id
        self.previewImageURLs = previewImageURLs
        self.recipeCount = recipeCount
        self.title = title
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.description = try values.decode(String.self, forKey: "description")
        self.id = try values.decode(Int.self, forKey: "id")
        self.previewImageURLs = try values.decode([URL].self, forKey: "preview_image_urls")
        self.recipeCount = try values.decode(Int.self, forKey: "recipe_count")
        self.title = try values.decode(String.self, forKey: "title")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(description, forKey: "description")
        try values.encode(id, forKey: "id")
        try values.encode(previewImageURLs, forKey: "preview_image_urls")
        try values.encode(recipeCount, forKey: "recipe_count")
        try values.encode(title, forKey: "title")
    }
}
