//
// Generated by openapi-generator
//

import Foundation

public struct Recipe: Codable {
    /// The unique recipe identifier.
    public var id: Int
    /// A URL to the main image of the recipe, or null if one was not specified.
    public var imageURL: URL?
    /// An array of ingredients used within the recipe.
    public var ingredients: [String]
    /// The date that the recipe was published in ISO8601 format.
    public var publishedAt: Date
    /// An array of steps to follow within the recipe.
    public var steps: [Step]
    /// The story behind the recipe.
    public var story: String
    /// The title of the recipe.
    public var title: String
    public var user: User

    public init(id: Int, imageURL: URL? = nil, ingredients: [String], publishedAt: Date, steps: [Step], story: String, title: String, user: User) {
        self.id = id
        self.imageURL = imageURL
        self.ingredients = ingredients
        self.publishedAt = publishedAt
        self.steps = steps
        self.story = story
        self.title = title
        self.user = user
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Int.self, forKey: "id")
        self.imageURL = try values.decodeIfPresent(URL.self, forKey: "image_url")
        self.ingredients = try values.decode([String].self, forKey: "ingredients")
        self.publishedAt = try values.decode(Date.self, forKey: "published_at")
        self.steps = try values.decode([Step].self, forKey: "steps")
        self.story = try values.decode(String.self, forKey: "story")
        self.title = try values.decode(String.self, forKey: "title")
        self.user = try values.decode(User.self, forKey: "user")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encodeIfPresent(imageURL, forKey: "image_url")
        try values.encode(ingredients, forKey: "ingredients")
        try values.encode(publishedAt, forKey: "published_at")
        try values.encode(steps, forKey: "steps")
        try values.encode(story, forKey: "story")
        try values.encode(title, forKey: "title")
        try values.encode(user, forKey: "user")
    }
}
