//
// Generated by openapi-generator
//

import Foundation

public struct User: Codable {
    /// A URL to the user profile image, or null if one was not specified.
    public var imageURL: URL?
    /// The name of the user.
    public var name: String

    public init(imageURL: URL? = nil, name: String) {
        self.imageURL = imageURL
        self.name = name
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.imageURL = try values.decodeIfPresent(URL.self, forKey: "image_url")
        self.name = try values.decode(String.self, forKey: "name")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(imageURL, forKey: "image_url")
        try values.encode(name, forKey: "name")
    }
}
