//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    /// All Collections
    ///
    /// Returns an array of all Collection models in display order.
    public static var getAllCollections: Request<[Collection]> {
        Request(path: "/api/collections/", method: "GET", id: "getAllCollections")
    }
}
