//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    /// Find Recipes in a Collection
    ///
    /// Returns an ordered array of Recipe models in the given Collection.
    public static func getCollectionRecipes(id: Int) -> Request<[Recipe]> {
        Request(path: "/api/collections/\(id)/recipes/", method: "GET", id: "getCollectionRecipes")
    }
}
