//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    /// Find a Recipe by ID
    ///
    /// Returns a specific Recipe model with the given identifier.
    public static func getRecipe(id: Int) -> Request<Recipe> {
        Request(path: "/api/recipes/\(id)/", method: "GET", id: "getRecipe")
    }
}
