//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    public static var users: Users {
        Users(path: "/api/v1/users")
    }

    public struct Users {
        /// Path: `/api/v1/users`
        public let path: String

        public var get: Request<Void> {
            Request(path: path, method: "GET", id: "listUsers")
        }
    }
}
