//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    public static func echoAddress(_ body: SharedAddress) -> Request<SharedAddress> {
        Request(path: "/echo-address", method: "POST", body: body, id: "echoAddress")
    }
}
