//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    public static var widgets: Widgets {
        Widgets(path: "/widgets")
    }

    public struct Widgets {
        /// Path: `/widgets`
        public let path: String
    }
}
