//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths.API {
    public var v1: V1 {
        V1(path: "\(path)/v1")
    }

    public struct V1 {
        /// Path: `/api/v1`
        public let path: String
    }
}
