//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths.API.V1 {
    public var users: Users {
        Users(path: "\(path)/users")
    }

    public struct Users {
        /// Path: `/api/v1/users`
        public let path: String

        public var get: Request<Void> {
            Request(path: path, method: "GET", id: "listUsers")
        }
    }
}
