//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths.API.V1 {
    public var teams: Teams {
        Teams(path: "\(path)/teams")
    }

    public struct Teams {
        /// Path: `/api/v1/teams`
        public let path: String

        public var get: Request<Void> {
            Request(path: path, method: "GET", id: "listTeams")
        }
    }
}
