//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    public static func validateAddress(_ body: SharedAddress) -> Request<Void> {
        Request(path: "/validate-address", method: "POST", body: body, id: "validateAddress")
    }
}
