//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    /// Get legacy item
    ///
    /// Use the replacement endpoint instead.
    public static var getLegacyItem: Request<Void> {
        Request(path: "/legacy", method: "GET", id: "getLegacyItem")
    }
}
