//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    public static var ignored: Request<Void> {
        Request(path: "/ignored", method: "GET", id: "ignored")
    }
}
