//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    public static var widgets: Widgets {
        Widgets(path: "/widgets")
    }

    public struct Widgets {
        /// Path: `/widgets`
        public let path: String

        /// List widgets
        public var get: Request<[Widget]> {
            Request(path: path, method: "GET", id: "listWidgets")
        }

        /// Create widget
        public func post(name: String) -> Request<Widget> {
            Request(path: path, method: "POST", body: ["name": name], id: "createWidget")
        }

        /// Delete widgets
        public var delete: Request<Void> {
            Request(path: path, method: "DELETE", id: "deleteWidgets")
        }
    }
}
