//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    /// All Recipes
    ///
    /// Returns an array of all Recipe models in order of most recently published.
    public static var getAllRecipes: Request<[Recipe]> {
        Request(path: "/api/recipes/", method: "GET", id: "getAllRecipes")
    }
}
