//
// Generated by openapi-generator
//

import Foundation
import Get

extension Paths {
    /// Find a Collection by ID
    ///
    /// Returns a single Collection model associated with the given identifier.
    public static func getCollection(id: Int) -> Request<Collection> {
        Request(path: "/api/collections/\(id)/", method: "GET", id: "getCollection")
    }
}
