//
// Generated by openapi-generator
//

import Foundation

/// Organization address schema
///
/// Organization-specific address property description remains on the property.
public struct SharedAddress: Codable {
    public var city: String?
    public var street: String?

    public init(city: String? = nil, street: String? = nil) {
        self.city = city
        self.street = street
    }

    public enum CodingKeys: String, CodingKey {
        case city = "city"
        case street = "street"
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        self.city = try values.decodeIfPresent(String.self, forKey: .city)
        self.street = try values.decodeIfPresent(String.self, forKey: .street)
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: CodingKeys.self)
        try values.encodeIfPresent(city, forKey: .city)
        try values.encodeIfPresent(street, forKey: .street)
    }
}
