//
// Generated by openapi-generator
//

import Foundation

/// Widget model
///
/// Entity config fixture
@available(*, deprecated, message: "Deprecated")
public struct Widget: Codable {
    public var count: Int16?
    public var created: Instant?
    public var id: Int
    @available(*, deprecated, message: "Deprecated")
    public var isActive: Bool
    public var link: URI?
    public var metadata: [String: AnyJSON]?
    public var ratio: Float32?
    public var status: Status
    public var zeta: String

    public enum Status: String, Codable, CaseIterable {
        case ready
        case notReady = "not-ready"
    }

    public init(count: Int16? = nil, created: Instant? = nil, id: Int, isActive: Bool? = nil, link: URI? = nil, metadata: [String: AnyJSON]? = nil, ratio: Float32? = nil, status: Status, zeta: String) {
        self.count = count
        self.created = created
        self.id = id
        self.isActive = isActive ?? true
        self.link = link
        self.metadata = metadata
        self.ratio = ratio
        self.status = status
        self.zeta = zeta
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.count = try values.decodeIfPresent(Int16.self, forKey: "count")
        self.created = try values.decodeIfPresent(Instant.self, forKey: "created")
        self.id = try values.decode(Int.self, forKey: "id")
        self.isActive = try values.decodeIfPresent(Bool.self, forKey: "active") ?? true
        self.link = try values.decodeIfPresent(URI.self, forKey: "link")
        self.metadata = try values.decodeIfPresent([String: AnyJSON].self, forKey: "metadata")
        self.ratio = try values.decodeIfPresent(Float32.self, forKey: "ratio")
        self.status = try values.decode(Status.self, forKey: "status")
        self.zeta = try values.decode(String.self, forKey: "zeta")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(count, forKey: "count")
        try values.encodeIfPresent(created, forKey: "created")
        try values.encode(id, forKey: "id")
        try values.encodeIfPresent(isActive, forKey: "active")
        try values.encodeIfPresent(link, forKey: "link")
        try values.encodeIfPresent(metadata, forKey: "metadata")
        try values.encodeIfPresent(ratio, forKey: "ratio")
        try values.encode(status, forKey: "status")
        try values.encode(zeta, forKey: "zeta")
    }
}
